cat_slug = [
    "kabel-komputer-or-laptop",
    "aksesoris-komputer-and-laptop",
    # "pc-gaming",
    # "card-reader",
    # "harddisk-case",
    # "aksesoris-penyimpanan-data-eksternal",
    # "smartphone-and-tablet",
    # "home-appliance",
    # "hobby",
    # "photography",
    # "olahraga-sepeda",
    # "olahraga-renang-and-diving",
    # "olahraga-lainnya",
    # "olahraga-lari",
    # "traveling",
    # "camping-and-hiking",
    # "senter-led",
    # "fitness-and-yoga",
    # "pelindung-tubuh",
    # "pakaian-and-sepatu-olahraga",
    # "audio",
    # "elektronik-rumah",
    # "cctv",
    # "mainan",
    # "remot-kontrol",
    # "perlengkapan-bayi",
    # "alat-kesehatan-and-kecantikan",
    # "perlengkapan-medis",
    # "perlengkapan-cukur-jenggot-and-kumis"
]